name: Build and Deploy to GHPages
on:
   push:
      branches:
         - main
jobs:
   build-deploy:
      runs-on: ubuntu-latest
      concurrency: ci-${{github.ref}}
      
      steps:
       - uses: actions/checkout@v3
         with:
            ref: main
            fetch-depth: 0
       - name: install
         run: |
            npm install
                     
       - name: deploy
         run: |
            git config --global user.email "<>"
            git config --global user.name "bot-github-actions"
            echo Deploying to GitHub Pages
            sh ./lib/deploy.sh
         
