name: Build and Deploy to GHPages
on:
   push:
jobs:
   build-deploy:
      runs-on: ubuntu-latest
      concurrency: ci-${{github.ref}}
      
      steps:
       - uses: actions/checkout@v3
         with:
            ref: main
            fetch-depth: 0         
       - name: deploy
         run: |
            echo Deploying to GitHub Pages
            sh ./lib/gh_pages_deploy.sh
         
