name: Build and Deploy to GHPages
on:
   push:
      branches:
         - main
jobs:
   build-deploy:
      runs-on: ubuntu-latest
      concurrency: ci-${{github.ref}}
      steps:
       - uses: actions/checkout@v3    
       
       - name: Build project
         run: |
            npm ci
            npm run build
       - name: create archive
         run: | 
            tar \
            --dereference --hard-dereference \
            --directory "dist" \
            -cvf "$RUNNER_TEMP/github-pages.tar" \
            --exclude=.git \
            --exclude=.github \
            .

       - name: deploy to ghp
         uses: actions/upload-pages-artifact@v1.0.4
         with:
            name: github-pages
            path: ${{ runner.temp }}
         
