name: Build and Deploy to GHPages
on:
   push:
      branches:
         - main
jobs:
   build-deploy:
      runs-on: ubuntu-latest
      concurrency: ci-${{github.ref}}
      steps:
       - uses: actions/checkout@v3         
       - name: deploy
         run: |
            git branch -la
            
            echo Deploying to GitHub Pages
            
            sh ./lib/gh_pages_deploy.sh
         
