name: Build and Deploy to GHPages
on:
   push:
      branches:
         - main
jobs:
   build-deploy:
      runs-on: ubuntu-latest
      concurrency: ci-${{github.ref}}
      steps:
       - uses: actions/checkout@v3
       - name: install
         run: npm install
         
       - name: deploy
         run: |
            git --version
            git config user.name "GitHub Actions Bot"
            git config user.email "<>"
            echo Deploying to GitHub Pages
            sh ./lib/deploy.sh
         
