name: Build and Deploy to GHPages
on:
   push:
      branches:
         - main
jobs:
   build-deploy:
      runs-on: ubuntu-latest
      concurrency: ci-${{github.ref}}
      steps:
       - name: checkout
         uses: actions/checkout@v2

       - name: deploy
         run: |
            echo Deploying to GitHub Pages
            sh ./lib/deploy.sh
         
