name: Build and Deploy to GHPages
on:
   push:
      branches:
         - main
jobs:
   build-deploy:
      runs-on: ubuntu-latest
      concurrency: ci-${{github.ref}}
      steps:
       - uses: actions/checkout@v3         
       - name: deploy
         run: |
            git branch -la
            export GITHUB_REPO=git@github.com:bncarey42/bncarey42.github.io.git
            export GITHUB_BRANCH=_gh-pages
            echo Deploying to GitHub Pages
            git checkout -b $GITHUB_BRANCH
            sh ./lib/gh_pages_deploy.sh
         
